version: '3'

services:
  spark-master:
    image: docker.io/bitnami/spark:2
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - dms_store=azure
      - azure_storage_account_name=devstoreaccount1
      - azure_storage_account_key=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
    user: root
    volumes:
      - ./spark/conf/log4j.properties:/opt/bitnami/spark/conf/log4j.properties
      - ./spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - ./spark/jars_dir:/opt/bitnami/spark/ivy:z
    ports:
      - '8885:8080'
      - '7077:7077'
    networks:
      - net

  spark-worker1:
    image: docker.io/bitnami/spark:2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - dms_store=azure
      - azure_storage_account_name=devstoreaccount1
      - azure_storage_account_key=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
    user: root
    volumes:
      - ./spark/conf/log4j.properties:/opt/bitnami/spark/conf/log4j.properties
      - ./spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - ./spark/jars_dir:/opt/bitnami/spark/ivy:z
    ports:
      - '8886:8081'   
    networks:
      - net
    depends_on:
      - spark-master

  spark-worker2:
    image: docker.io/bitnami/spark:2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - dms_store=azure
      - azure_storage_account_name=devstoreaccount1
      - azure_storage_account_key=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
    user: root
    volumes:
      - ./spark/conf/log4j.properties:/opt/bitnami/spark/conf/log4j.properties
      - ./spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - ./spark/jars_dir:/opt/bitnami/spark/ivy:z
    ports:
      - '8887:8082'   
    networks:
      - net
    depends_on:
      - spark-master

  livy-server:
    container_name: livy_server
    build: ./livy-server/
    command: ["sh", "-c", "/opt/bitnami/livy/bin/livy-server"]
    user: root
    volumes:
      - ./livy-server/conf/:/opt/bitnami/livy/conf/
      - ./livy-server/target/:/target/
      - ./livy-server/data/:/data/
    ports:
      - '8998:8998'
    networks:
      - net
    depends_on:
      - spark-master
      - spark-worker1
      - spark-worker2

  # db:
  #   container_name: pg_container
  #   image: postgres
  #   restart: always
  #   environment:
  #       POSTGRES_USER: "postgres"
  #       POSTGRES_PASSWORD: "12345"
  #       POSTGRES_DB: "db"
  #       POSTGRES_HOST_AUTH_METHOD: trust
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - net
        
volumes:
  pg_data:

networks:
  net:
    driver: bridge