FROM jboss/jbpm-server-full:latest
COPY business-central.war kie-server.war /opt/jboss/wildfly/standalone/deployments/
COPY deployment-descriptor.xml /home/
MAINTAINER sandeep.rana(aimhigh.excel@gmail.com)
